### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/PublicArtManagementApp#1]
Nothing shows up. It is because we changed the server?
![screen shot 2015-03-30 at 3 35 56 pm](https://cloud.githubusercontent.com/assets/6502307/6906139/82316438-d6f2-11e4-8757-0ee51d366725.png)

**Comment by vnguyen9** [comment]
![screen shot 2015-03-30 at 3 37 28 pm](https://cloud.githubusercontent.com/assets/6502307/6906173/b03f0bc8-d6f2-11e4-911a-789cffb8204f.png)

**Comment by CarlSteven** [comment]
Yep, it is pointing to the wrong URL as you can see in the console. It is supposed to be:
https://www.housuggest.org:8443/ArtApp/

Can easily be changed in the app.js and pushed.
